---
galaxy_info:
  author: SBNB Team
  description: Mount encrypted LUKS data disk
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - luks
    - encryption
    - storage

dependencies: []
