---
# Docker role handlers

- name: Reset Docker systemd failure counter
  ansible.builtin.command:
    cmd: systemctl reset-failed docker
  changed_when: false
  failed_when: false
  listen: Restart Docker

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
