---
# Wordlists for generating human-readable VM names

sbnb_adverbs:
  - swift
  - gentle
  - bright
  - calm
  - bold
  - keen
  - quick
  - warm
  - cool
  - soft

sbnb_adjectives:
  - smart
  - happy
  - shy
  - wild
  - keen
  - brave
  - wise
  - fair
  - kind
  - proud

sbnb_animals:
  - pika
  - fox
  - owl
  - bear
  - wolf
  - lynx
  - hare
  - deer
  - hawk
  - seal
  - orca
  - mink
