---
galaxy_info:
  author: SBNB Team
  description: Run Grafana Alloy monitoring with IPMI exporter
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - monitoring
    - grafana
    - prometheus
    - ipmi

dependencies: []
