---
galaxy_info:
  author: SBNB Team
  description: Run RAGFlow RAG platform
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - ragflow
    - rag
    - llm
    - ai

dependencies: []
