---
galaxy_info:
  author: SBNB Team
  description: Install NVIDIA drivers and container toolkit
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - nvidia
    - gpu
    - cuda
    - docker

dependencies: []
