---
galaxy_info:
  author: SBNB Team
  description: Run TP-Link Omada Controller
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - omada
    - tplink
    - network
    - controller

dependencies: []
